### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by claytondukes** [mcarella/godzillamonsterlogs#1]
Hi, your project looks fun, but unfortunately, we own the copyright to "LogZilla" (http://www.logzilla.net).
Please change the name of your project so that our users do not get confused :)

**Comment by mcarella** [comment]
Hi clayton I'm sorry I never heard about logZilla before I will change the
name. Sorry for that.

Best regards,
Matteo

Il venerdì 21 agosto 2015, claytondukes notifications@github.com ha
scritto:

> Hi, your project looks fun, but unfortunately, we own the copyright to
> "LogZilla" (http://www.logzilla.net).
> Please change the name of your project so that our users do not get
> confused :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mcarella/logzilla/issues/1.

## 

Sent from Gmail Mobile

**Comment by claytondukes** [comment]
No worries, thanks :)

From: mcarella
Reply-To: mcarella/logzilla
Date: Friday, August 21, 2015 at 9:14 AM
To: mcarella/logzilla
Cc: claytondukes
Subject: Re: [logzilla] Copyright (#1)

Hi clayton I'm sorry I never heard about logZilla before I will change the
name. Sorry for that.

Best regards,
Matteo

Il venerdì 21 agosto 2015, claytondukes <notifications@github.com<mailto:notifications@github.com>> ha
scritto:

> Hi, your project looks fun, but unfortunately, we own the copyright to
> "LogZilla" (http://www.logzilla.net).
> Please change the name of your project so that our users do not get
> confused :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mcarella/logzilla/issues/1.

## 

Sent from Gmail Mobile

**Comment by claytondukes** [comment]
Hi, you'll need to modify your code as well to remove any references to "logzilla", sorry for the trouble :)

**Comment by mcarella** [comment]
Done! :)

**Comment by claytondukes** [comment]
Thanks for being so cool about it :+1:

**Comment by mcarella** [comment]
No problem guys 😁

Il lunedì 21 settembre 2015, Clayton Dukes notifications@github.com ha
scritto:

> Closed #1 https://github.com/mcarella/godzillamonsterlogs/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mcarella/godzillamonsterlogs/issues/1#event-414672120
> .

## 

Sent from Gmail Mobile
